services:
  _defaults:
    autowire: true
    autoconfigure: true

  GabrielDosAnjosBr\DomainEvents\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Doctrine/'
      - '../src/DomainEventBundle.php'